// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKX2Ozobf4iCzrDryCnRG6NPizgE7HCdk',
    appId: '1:373611536397:web:89ecbf2a7df6f462c1b544',
    messagingSenderId: '373611536397',
    projectId: 'fir-flutter-codelab-6132b',
    authDomain: 'fir-flutter-codelab-6132b.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-6132b.appspot.com',
    measurementId: 'G-64SBJHNSZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHAX2_9dMUw-nVPC6cDYxd0fBzk1QK5O0',
    appId: '1:373611536397:android:1a9ae0819c815323c1b544',
    messagingSenderId: '373611536397',
    projectId: 'fir-flutter-codelab-6132b',
    storageBucket: 'fir-flutter-codelab-6132b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDidt2jeci8SKAHJOA0enupsGuVXqI_mw',
    appId: '1:373611536397:ios:cfbcc73f277833c3c1b544',
    messagingSenderId: '373611536397',
    projectId: 'fir-flutter-codelab-6132b',
    storageBucket: 'fir-flutter-codelab-6132b.appspot.com',
    iosClientId: '373611536397-kbtvbijq5fasqb0dj142frjd043md51e.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDidt2jeci8SKAHJOA0enupsGuVXqI_mw',
    appId: '1:373611536397:ios:cfbcc73f277833c3c1b544',
    messagingSenderId: '373611536397',
    projectId: 'fir-flutter-codelab-6132b',
    storageBucket: 'fir-flutter-codelab-6132b.appspot.com',
    iosClientId: '373611536397-kbtvbijq5fasqb0dj142frjd043md51e.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
